### ISSUE TITLE
✨ feat: implement user feature

### ISSUE THREAD

**Issue by jsh1147** [codeit-sprint-fe10/Albaform#1]
## 📝 Description

- 유저 기능 구현

## ✅ To-Do List

- [x] 유저 관련 API 추가
- [x] 유저 전역 상태 추가
- [x] 접근 관련 미들웨어 추가
